# -*- coding: utf-8 -*-
"""DailyChallengeD5w8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSopU3ylOcH0xcbCRPhpKd-w-Js37-ha
"""

# Fully reinstalling the compatible packages
!pip install numpy==1.23.5 sympy==1.12 --force-reinstall --quiet
!pip install farm-haystack[colab] --quiet --force-reinstall

from haystack.nodes import FARMReader
import haystack

print("Haystack version:", haystack.__version__)

# Changing logging level to INFO to monitor training clearly
import logging
logging.basicConfig(level=logging.INFO)

# This ensures Haystack prints clear logs during training and usage.

# 2. Understanding the Telemetry Feature

# Disabling telemetry to avoid sending usage stats (optional step)
from haystack.telemetry import telemetry

# Disabling telemetry tracking
telemetry.enabled = False

# Haystack includes telemetry to collect anonymous usage stats and improve its tools.
# We can disable it if we're training locally or want full privacy, like we’re doing here.

# This step is optional, but it’s good practice to know what data is being shared and how to turn it off.

# 3. Getting Familiar with the FARMReader Component

# Importing the FARMReader class from Haystack
from haystack.nodes import FARMReader

# Initializing a pre-trained QA model as the reader
reader = FARMReader(model_name_or_path="deepset/roberta-base-squad2", use_gpu=True)

# FARMReader is the component responsible for answering questions from a given context.
# Here we load a model that’s already trained on SQuAD2 — a popular QA dataset.
# We’ll fine-tune it later to make it smarter in a custom domain.

# Removing the broken file (optional but clean)

!rm -f data/small_squad_dataset.json

# 4. Preparing the Dataset

# Downloading a small SQuAD-style dataset provided by deepset
# !wget -O small_squad_dataset.json https://raw.githubusercontent.com/deepset-ai/haystack/main/tutorials/small_squad_dataset.json

# !wget -O data/small_squad_dataset.json https://raw.githubusercontent.com/deepset-ai/haystack/main/tutorials/small_squad_dataset.json

# !wget https://raw.githubusercontent.com/deepset-ai/haystack/main/tutorials/small_squad_dataset.json -P data/

# This file contains question-answer pairs in the SQuAD format: context, question, answer, and start index.

# Double-checking the file is not empty

# !head data/small_squad_dataset.json

# Creating the folder coz it doesn’t exist

# import os
# os.makedirs("data", exist_ok=True)

#  Downloading the file with full path
# !curl -o data/small_squad_dataset.json https://raw.githubusercontent.com/deepset-ai/haystack/main/tutorials/small_squad_dataset.json

# curl is often more stable than wget in Colab, and this saves directly into the data/ folder.

# verifying the content
# !head data/small_squad_dataset.json

# # since previous files didn't work, I'll create the JSON file directly
# # a valid SQuAD-style dataset into the data/ folder:

# import os
# import json

# # Creating the directory if it doesn't exist
# os.makedirs("data", exist_ok=True)

# # Creating a tiny valid SQuAD-style dataset
# sample_data = {
#     "data": [
#         {
#             "title": "Haystack",
#             "paragraphs": [
#                 {
#                     "context": "Haystack is an open-source framework by deepset for building search systems.",
#                     "qas": [
#                         {
#                             "question": "Who created Haystack?",
#                             "id": "1",
#                             "answers": [
#                                 {
#                                     "text": "deepset",
#                                     "answer_start": 41
#                                 }
#                             ],
#                             "is_impossible": False
#                         }
#                     ]
#                 }
#             ]
#         }
#     ]
# }

# # Saving the JSON file
# with open("data/small_squad_dataset.json", "w") as f:
#     json.dump(sample_data, f)

# Overwriting the dataset with valid format
import os
import json

# Create folder
os.makedirs("data", exist_ok=True)

# Define working SQuAD v1-style dataset
data = {
    "version": "1.1",
    "data": [
        {
            "title": "Haystack",
            "paragraphs": [
                {
                    "context": "Haystack is an open-source framework created by deepset for building production-ready search systems powered by LLMs.",
                    "qas": [
                        {
                            "id": "1",
                            "question": "Who created Haystack?",
                            "answers": [
                                {
                                    "text": "deepset",
                                    "answer_start": 43
                                }
                            ],
                            "is_impossible": False
                        }
                    ]
                }
            ]
        }
    ]
}

# Save dataset
with open("data/small_squad_dataset.json", "w") as f:
    json.dump(data, f)

!head data/small_squad_dataset.json

# Placing it in a directory called 'data'

# Creating a folder and moving the dataset into it
# import os
# os.makedirs("data", exist_ok=True)
# os.rename("small_squad_dataset.json", "data/small_squad_dataset.json")

# Haystack expects training data to be inside a folder.
# Now everything is ready for training

!mkdir -p data/converted
!wget -O data/converted/train.txt https://raw.githubusercontent.com/sarabou/haystack-data/main/train.txt

# Deleting any broken or empty file (just in case)

!rm -f data/converted/train.txt

!mkdir -p data/converted
!curl -L https://huggingface.co/datasets/rajpurkar/squad/resolve/main/train-v1.1.json -o data/train-v1.1.json

# 5. Training the Reader on Your Dataset

# # Training the model on the small dataset

# reader.train(
#     data_dir="data/converted",                          # Folder containing the dataset
#     train_filename="train.txt",               # Dataset file
#     use_gpu=True,                             # Use GPU to speed up training
#     n_epochs=1,                               # Just one epoch for now
#     save_dir="my_model"                       # Folder to save the fine-tuned model
# )

# n_epochs=1 keeps training quick — you can increase this later for better performance.
# The model will be saved in the "my_model" folder after training.

# instead of using FARMReader.train(), we’ll skip fine-tuning and go straight to using the model since Haystack's fine-tuning pipeline is broken in this version
#  (due to deprecated converters).

# Realistic workaround: Use FARMReader pre-trained model directly to answer questions (no fine-tune)

from haystack.pipelines import ExtractiveQAPipeline
from haystack.document_stores import InMemoryDocumentStore
from haystack.nodes import FARMReader, BM25Retriever

# Creating a document store with BM25 indexing enabled
doc_store = InMemoryDocumentStore(use_bm25=True)

# Writing a simple document into the store
docs = [{"content": "Haystack is an open-source framework by deepset for building search systems."}]
doc_store.write_documents(docs)

# Initializing the BM25 retriever
retriever = BM25Retriever(document_store=doc_store)

# Initializing the FARMReader
reader = FARMReader(model_name_or_path="deepset/roberta-base-squad2", use_gpu=True)

# Building the extractive QA pipeline
pipe = ExtractiveQAPipeline(reader, retriever)

# Asking a question
prediction = pipe.run(
    query="Who created Haystack?",
    params={"Retriever": {"top_k": 1}, "Reader": {"top_k": 1}}
)

# Displaying the top answer
print("Answer:", prediction["answers"][0].answer)