# -*- coding: utf-8 -*-
"""Exercise 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_VTfj83d6oUsN-_hJyqKCPZkO-btToX
"""

from google.colab import files
files.upload()

import pandas as pd

sleep_data = pd.read_csv('Time Americans Spend Sleeping.csv')
credit_card_data = pd.read_csv('clean_dataset.csv')
mental_health_data = pd.read_csv('Mental health Depression disorder Data.csv')

print(sleep_data.head(5))
print(mental_health_data.head(5))
print(credit_card_data.head(5))

# Sleep Data:
# This dataset contains information about the average hours of sleep per day in the U.S. over various years (2003-2019).
# It includes columns such as the year, period, average hours of sleep, standard error, age group, activity, and sex.

# Mental Health Data:
# This dataset presents global trends in mental health disorders, including statistics on schizophrenia, bipolar disorder,
# eating disorders, anxiety, drug use disorders, depression, and alcohol use disorders for various countries from 1990 onwards.

# Credit Card Data:
# This dataset contains information about individuals' credit card approvals, including demographic information (gender, age, ethnicity),
# financial details (debt, income, credit score), and approval status for credit cards. It includes columns related to employment,
# marital status, industry, and credit approval outcomes.