# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHhGzroCYRQmuTQOYyfKR_Vav8rIoeUi
"""

# What is Data Analysis?
# Data analysis is the process of gathering, organizing, and examining data to uncover patterns, trends, and useful insights. It transforms raw data into meaningful information that helps with decision-making.

# Why is Data Analysis Important Today?
# In our tech-driven world, data is constantly being generated. Whether it’s businesses, governments, or individuals, data analysis helps make sense of this information. It’s crucial for predicting trends, improving operations, and solving problems. Companies use it to understand their customers, governments rely on it for making informed policies, and even social media platforms leverage it to improve user experience.

# Three Areas Where Data Analysis is Used:
# Social Media – Platforms like Instagram and TikTok use data to understand user behavior, recommend content, flag fake accounts, and serve personalized ads.
# Healthcare – Medical researchers and professionals analyze data to track disease trends, improve treatments, and offer better patient care.
# Finance – Banks analyze customer transactions to spot fraud, assess risk, and make informed investment choices.

# In short, data analysis plays a crucial role in shaping industries and our daily lives, making it an indispensable tool in modern society.