# -*- coding: utf-8 -*-
"""Exercise4+5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V0DBKCTm3q7ERp29gGOeQXuv2Me0Yxz
"""

from google.colab import files
files.upload()

import pandas as pd

Iris = pd.read_csv("Iris.csv")

Iris.head()

"""Quantitative columns: SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm.
Qualitative column: Species (categorical label for flower type).

SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm → Quantitative because they are numerical measurements that represent the size of the flower parts. we can perform math operations on them (like finding the average).
Species → Qualitative because it categorizes the flowers into different types (like Iris-setosa). It doesn’t have a num value, and we can’t do math with it.
"""

Iris.describe()

import matplotlib.pyplot as plt

data = pd.read_csv("Iris.csv")
plt.plot(data['SepalLengthCm'], data['SepalWidthCm'])
plt.show()