# -*- coding: utf-8 -*-
"""Exercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzBtOkPIdolLcxL-gu94H8LKFImUdGSt
"""

# # 1. How Much Sleep Do Americans Really Get?
# Year → Quantitative (Numeric values representing years)
# Period → Qualitative (Categories like "Annual")
# Avg hrs per day sleeping → Quantitative (Numeric values representing hours)
# Standard Error → Quantitative (Statistical error in numeric form)
# Type of Days → Qualitative (Categorical values like "All days")
# Age Group → Qualitative (Groups like "15 years and over")
# Activity → Qualitative (Describes actions like "Sleeping")
# Sex → Qualitative (Categorical: "Male", "Female", "Both")
# 2. Global Trends in Mental Health Disorders
# Entity → Qualitative (Represents countries or regions like "Afghanistan")
# Code → Qualitative (Country codes like "AFG")
# Year → Quantitative (Numeric year values)
# Schizophrenia (%) → Quantitative (Numeric percentage of disorder prevalence)
# Bipolar disorder (%) → Quantitative (Numeric percentage values)
# Eating disorders (%) → Quantitative (Numeric percentage values)
# Anxiety disorders (%) → Quantitative (Numeric percentage values)
# Drug use disorders (%) → Quantitative (Numeric percentage values)
# Depression (%) → Quantitative (Numeric percentage values)
# Alcohol use disorders (%) → Quantitative (Numeric percentage values)
# 3. Credit Card Approvals Dataset
# Gender → Qualitative (Categorical: "Male", "Female")
# Age → Quantitative (Numeric values in years)
# Debt → Quantitative (Numeric values representing debt amount)
# Married → Qualitative (Binary categorical: "Yes", "No")
# BankCustomer → Qualitative (Categorical: Indicates if a person is a bank customer)
# Industry → Qualitative (Categorical: Sectors like "Materials", "Industrials")
# Ethnicity → Qualitative (Categorical: "White", "Black", etc.)
# YearsEmployed → Quantitative (Numeric: Number of years employed)
# PriorDefault → Qualitative (Binary categorical: "Yes", "No")
# Employed → Qualitative (Binary categorical: "Yes", "No")
# CreditScore → Quantitative (Numeric credit score)
# DriversLicense → Qualitative (Binary categorical: "Yes", "No")
# Citizen → Qualitative (Categorical: "ByBirth", "ByOtherMeans")
# ZipCode → Qualitative (Categorical: Used as an identifier, not for calculations)
# Income → Quantitative (Numeric: Represents amount of income)
# Approved → Qualitative (Binary categorical: "Yes", "No")
# Summary:
# Quantitative data = Numbers that represent measurable amounts (e.g., Age, Income, Credit Score).
# Qualitative data = Labels or categories that describe something (e.g., Gender, Job Industry, Citizenship).