# -*- coding: utf-8 -*-
"""Exercises1+2+3D2W2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeQS8hoMnQvDp7YmUnWFZDP2qcOUB1PJ
"""

#  Exercise 1
# A company’s financial reports stored in an Excel file. Structured
# Photographs uploaded to a social media platform. Unstructured
# A collection of news articles on a website. Unstructured
# Inventory data in a relational database. Structured
# Recorded interviews from a market research study. Unstructured

# Exercise 2

# - A series of blog posts about travel experiences.
# We can create a table with these columns:
# Post Title
# Date
# Sentiment (Positive, Negative, Neutral)
# We can determine the sentiment by checking for positive/negative words.

# - Audio recordings of customer service calls.
# We can create a table with these columns: Transcript, Date, and Sentiment (Positive, Negative, Neutral)
# We can determine the sentiment by converting speech to text and analyzing the words used.

# - Handwritten notes from a brainstorming session:
# We can convert handwriting to text then organize them into a table with columns for Topic, Key Ideas, Contributor, and Date.

# A video tutorial on cooking:
# We can transcribe the video into text and create a structured table with these columns: Recipe Name, Ingredients, Steps, and Cooking Time.
# This makes it easier to search, filter, and analyze cooking tutorials.

# Exercise 3
!pip install pandas

from google.colab import files
files.upload()

import pandas as pd
train = pd.read_csv("train.csv")

train.head()