# -*- coding: utf-8 -*-
"""Exercises6D2W2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRxEwRv7g6A_zGXvaMLz7Gk6xvI5qvin
"""

from google.colab import files
files.upload()

import pandas as pd
post = pd.read_json("posts.json")

post.head(5)