# -*- coding: utf-8 -*-
"""Exercises4D2W2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFETsFQ_wHgplA31cp104edv7VFjLfe0
"""

!pip install pandas
from google.colab import files
files.upload()

import pandas as pd

Iris = pd.read_csv("Iris_dataset.csv")

Iris.head(5)