# -*- coding: utf-8 -*-
"""DailyChallengeD4W2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VI-YM0HUW_7-kXbA-YLKgzW9oMYN6UFp
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
files.upload()

data = pd.read_csv("2019.csv")
print (data.head())

# to check missing data
df = pd.DataFrame(data)
missing_data = df.isnull()

print(missing_data.head())

# To count missing values in each column
missing_counts = df.isnull().sum()
print(missing_counts)

# scatter plot to investigate the relationship between ‘Social support’ and ‘Score’.
sns.lmplot(x='Social support', y='Score', data=data, aspect=1.5, height=5)
plt.title('Social Support and Happiness')
plt.show()
# conclusion : More social support = Generally higher happiness.
# But it's not a perfect rule—some people may still be unhappy despite strong social support.

import matplotlib.pyplot as plt
import seaborn as sns

print(df.columns)

# Assuming df is your dataset containing GDP, Life Expectancy, and Region
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 10))
# GDP per Capita by Region
sns.boxplot(x="Country or region", y="GDP per capita", data=df, ax=ax1)
ax1.set_title('GDP per Capita by Region')
ax1.set_xticklabels(ax1.get_xticklabels(), rotation=45)

# Healthy Life Expectancy by Region
sns.boxplot(x="Country or region", y="Healthy life expectancy", data=df, ax=ax2)
ax2.set_title('Healthy Life Expectancy by Region')
ax2.set_xticklabels(ax2.get_xticklabels(), rotation=45)

plt.tight_layout()
plt.show()

